spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}