server:
  port: 8080

spring:
  application:
    name: ToDo Tasks

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml